POST http://127.0.0.1:8000/api/auth/login-cookie/
Content-Type: application/json

{
  "email": "joanthanmuangala@gmail.com",
  "password": "Kadanga2003"
}
###
GET http://localhost:8000/api/academique/coordons/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODc5NzI1LCJpYXQiOjE3Njg4Nzg4MjUsImp0aSI6IjlhOTc3ZmE1YjlmMzRhYmU5MDZlMWQzNTU5ZDc3NWRiIiwidXNlcl9pZCI6IjEifQ.r58FfjvREHQ6cXz-oq32ttEx0thfO36_7gTitlvmJh0
###
GET http://127.0.0.1:8000/api/cours/1/documents/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NDE4MjQxLCJpYXQiOjE3Njg0MTc5NDEsImp0aSI6IjFhMWVmNTljNzc1YTQzMDA5NjE3YjUwNjgwNjAyNDM0IiwidXNlcl9pZCI6IjEifQ.G73ox9GPJZF7ijEzx5LEyiChl1alF-Lf_vSUy8Y5fss

###
POST http://127.0.0.1:8000/api/cours/1/documents/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NDE4MjQxLCJpYXQiOjE3Njg0MTc5NDEsImp0aSI6IjFhMWVmNTljNzc1YTQzMDA5NjE3YjUwNjgwNjAyNDM0IiwidXNlcl9pZCI6IjEifQ.G73ox9GPJZF7ijEzx5LEyiChl1alF-Lf_vSUy8Y5fss
Content-Type: application/json

{
  "titre": "Notes – Cardiologie",
  "categorie": "notes"
}


###
GET http://127.0.0.1:8000/api/auth/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODY3ODE3LCJpYXQiOjE3Njg4NjY5MTcsImp0aSI6IjdmOTIxODBkZTBkMzQ1YTY4OGJlMmQ0YTZlYmQ5MjMxIiwidXNlcl9pZCI6IjEifQ.zDYraF_mHgiPUl9oi1aFlr1ynHH0LdoAc8APE6JdqNo
###
PATCH http://127.0.0.1:8000/api/auth/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODIwNTU3LCJpYXQiOjE3Njg4MTk2NTcsImp0aSI6IjRjNzRhOWQzZmM1MDRkYzJiZmVjN2QzOWYwZTQxZWE2IiwidXNlcl9pZCI6IjEifQ.0CQpsOD8WyoQbTk4KvNh_EtJgHB3nMwZlxD4bMARb7Q
Content-Type: application/json

{
  "telephone": "0812345678",
  "role" : "ADMIN",
  "bio": "Étudiant B3 – passionné de physique"
}


###
GET http://127.0.0.1:8000/api/auth/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODI0MjA5LCJpYXQiOjE3Njg4MjMzMDksImp0aSI6IjM1MTU2MGY5MzllZjQ3M2ZhZjM1MDU5OWZhZjMyOGYwIiwidXNlcl9pZCI6IjEifQ.ZkHpJHFEHzAWWqcj5_YiD0cytc3xLpvb-On53sc69TM
###

POST http://127.0.0.1:8000/api/create-encadreur/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MzMyNDM2LCJpYXQiOjE3NjgzMzIxMzYsImp0aSI6IjY3MTFmM2NmZTliMjRhZGE4ZjlhNGE4Njk0ZDMyMGNhIiwidXNlcl9pZCI6IjEifQ.Kgc32ifr9zRpVv8KiSLZ19DbAKIbLjsKsXIJYiyup9s

###

POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
  "email": "joanthanmuangala@gmail.com",
  "password": "Kadanga2003"
}

###
POST http://127.0.0.1:8000/api/auth/refresh-cookie/

###
POST http://127.0.0.1:8000/api/auth/logout-cookie/
