# Generated by Django 5.2.4 on 2026-01-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='annee',
            field=models.IntegerField(default=2025, max_length=4),
        ),
    ]
