# Generated by Django 5.2.4 on 2026-01-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_promotion_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
    ]
