# Generated by Django 5.2.4 on 2026-01-14 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_cours_promotion_alter_cours_encadreur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='encadreur',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='promotion',
        ),
        migrations.AddField(
            model_name='cours',
            name='encadreurs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'ENCADREUR'}, related_name='cours_encadres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='cours', to='academique.promotion'),
        ),
    ]
