# Generated by Django 5.2.4 on 2026-01-13 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_cours_promotion_alter_cours_encadreur'),
        ('users', '0003_user_bio_user_telephone_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profils/IMG-20250807-WA0097.jpg', null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academique.promotion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
