# Generated by Django 5.2.4 on 2026-01-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_cours_promotion_alter_cours_encadreur'),
        ('users', '0005_alter_user_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academique.promotion'),
        ),
    ]
